version: '3.8'

services:
  db:
    container_name: LearnGrow_db
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=LearnGrow
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data

  frontend:
    container_name: LearnGrow_frontend
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - db

  backend:
    container_name: LearnGrow_backend
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "${APP_HOST_PORT}:8000"
    depends_on:
      - db
    restart: always
    env_file: .env


volumes:
  postgres_data: