# Generated by Django 5.1.3 on 2024-11-19 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('time_registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video', models.FileField(null=True, upload_to='videos/%Y/%m/%d/')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LearnGrow.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LearnGrow.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('time_registration', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LearnGrow.classes')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LearnGrow.subjects'),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LearnGrow.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Images_for_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LearnGrow.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Academic_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(null=True)),
                ('solving', models.FileField(null=True, upload_to='files/%Y/%m/%d/')),
                ('date_of_delivery', models.DateTimeField(null=True)),
                ('assessment_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='LearnGrow.assessments')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LearnGrow.statuses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LearnGrow.students')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LearnGrow.tasks')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LearnGrow.teachers'),
        ),
    ]
