# Generated by Django 5.1.3 on 2024-11-20 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnGrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_record',
            name='assessment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LearnGrow.assessments'),
        ),
        migrations.AlterField(
            model_name='academic_record',
            name='date_of_delivery',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='academic_record',
            name='solving',
            field=models.FileField(upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='assessments',
            name='assessment',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
