# Generated by Django 5.1.3 on 2024-11-22 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnGrow', '0003_alter_academic_record_date_of_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_record',
            name='assessment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='LearnGrow.assessments'),
        ),
    ]
