# Generated by Django 5.1.3 on 2025-01-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnGrow', '0006_rename_user_id_students_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic_record',
            old_name='assessment_id',
            new_name='assessment',
        ),
        migrations.RenameField(
            model_name='academic_record',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='academic_record',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='academic_record',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='images_for_tasks',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='lessons',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='materials',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
